"""
embed_web.py — turn web/ into src/generated/WebAssets.h before every build.

PlatformIO runs this as a pre-script (see platformio.ini). The page is authored
as ordinary files:

    web/index.html   markup; references app.css and app.js
    web/app.css      styles
    web/app.js       behaviour

and shipped as ONE gzipped response. Inlining keeps it to a single request, which
matters on a single-threaded ESP32 web server over a phone hotspot; gzip cuts it
to roughly a third.

Two details that are easy to get wrong:

* gzip is called with mtime=0. Otherwise the gzip header embeds the build time,
  every build changes the firmware image, and two builds of identical source
  can never be compared byte for byte.
* The header is rewritten only when its content changes, so an unchanged page
  does not force a recompile of everything that includes it.

It also writes web/dist/index.html — the same page, uncompressed — for local
preview and for the design checks, which need to read it as HTML.
"""

import gzip
import pathlib

try:
    Import("env")  # noqa: F821 — provided by PlatformIO/SCons
    PROJECT_DIR = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:  # run by hand: python tools/embed_web.py
    PROJECT_DIR = pathlib.Path(__file__).resolve().parent.parent

WEB = PROJECT_DIR / "web"
OUT_HEADER = PROJECT_DIR / "src" / "generated" / "WebAssets.h"
OUT_PREVIEW = WEB / "dist" / "index.html"

CSS_TAG = '<link rel="stylesheet" href="app.css">'
JS_TAG = '<script src="app.js"></script>'


def build_page() -> str:
    html = (WEB / "index.html").read_text(encoding="utf-8")
    css = (WEB / "app.css").read_text(encoding="utf-8")
    js = (WEB / "app.js").read_text(encoding="utf-8")
    for tag in (CSS_TAG, JS_TAG):
        if html.count(tag) != 1:
            raise SystemExit(f"embed_web: expected exactly one {tag!r} in web/index.html")
    if "</script" in js:
        raise SystemExit("embed_web: app.js contains '</script' and would end the inline block early")
    html = html.replace(CSS_TAG, "<style>\n" + css + "</style>")
    html = html.replace(JS_TAG, "<script>\n" + js + "</script>")
    return html


def to_header(gz: bytes, raw_len: int) -> str:
    lines = []
    for i in range(0, len(gz), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in gz[i:i + 16]) + ",")
    return (
        "// GENERATED by tools/embed_web.py from web/ - do not edit, edit web/ instead.\n"
        "#pragma once\n"
        "#include <Arduino.h>\n\n"
        f"// {raw_len} bytes of HTML, gzipped to {len(gz)}.\n"
        f"static const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n"
        + "\n".join(lines) + "\n};\n"
    )


def main() -> None:
    page = build_page()
    raw = page.encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    OUT_PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    OUT_PREVIEW.write_text(page, encoding="utf-8", newline="\n")

    header = to_header(gz, len(raw))
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    if not OUT_HEADER.exists() or OUT_HEADER.read_text(encoding="utf-8") != header:
        OUT_HEADER.write_text(header, encoding="utf-8", newline="\n")
        print(f"embed_web: page {len(raw)} B -> {len(gz)} B gzipped, header updated")
    else:
        print(f"embed_web: page unchanged ({len(gz)} B gzipped)")


main()
